name: vrui
channels:
  - conda-forge
  - defaults
dependencies:
  - babel=2.17.0=pyhd8ed1ab_0
  - backrefs=5.8=pyhd8ed1ab_0
  - brotli-python=1.1.0=py312haafddd8_3
  - bzip2=1.0.8=hfdf4475_7
  - ca-certificates=2025.7.14=hbd8a1cb_0
  - certifi=2025.7.14=pyhd8ed1ab_0
  - cffi=1.17.1=py312hf857d28_0
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - click=8.2.1=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - ghp-import=2.1.0=pyhd8ed1ab_2
  - h2=4.2.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=h120a0e1_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - libcxx=20.1.8=h3d58e20_1
  - libexpat=2.7.1=h21dd04a_0
  - libffi=3.4.6=h281671d_1
  - liblzma=5.8.1=hd471939_2
  - libsqlite=3.50.3=h875aaf5_1
  - libzlib=1.3.1=hd23fc13_2
  - markdown=3.8.2=pyhd8ed1ab_0
  - markupsafe=3.0.2=py312h3520af0_1
  - mergedeep=1.3.4=pyhd8ed1ab_1
  - mkdocs=1.6.1=pyhd8ed1ab_1
  - mkdocs-get-deps=0.2.0=pyhd8ed1ab_1
  - mkdocs-material=9.6.15=pyhd8ed1ab_0
  - mkdocs-material-extensions=1.3.1=pyhd8ed1ab_1
  - ncurses=6.5=h0622a9a_3
  - openssl=3.5.1=hc426f3f_0
  - packaging=25.0=pyh29332c3_1
  - paginate=0.5.7=pyhd8ed1ab_1
  - pathspec=0.12.1=pyhd8ed1ab_1
  - pip=25.1.1=pyh8b19718_0
  - platformdirs=4.3.8=pyhe01879c_0
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pymdown-extensions=10.16=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.11=h9ccd52b_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.12=8_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py312h3520af0_2
  - pyyaml-env-tag=1.1=pyhd8ed1ab_0
  - readline=8.2=h7cca4af_2
  - requests=2.32.4=pyhd8ed1ab_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - tk=8.6.13=hf689a15_2
  - tzdata=2025b=h78e105d_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - watchdog=6.0.0=py312h01d7ebd_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - yaml=0.2.5=h0d85af4_2
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstandard=0.23.0=py312h01d7ebd_2
prefix: /usr/local/Caskroom/miniconda/base/envs/vrui
